Funcionalidad 195/vista de personas con acceso otorgado
TallerDeDesarrollo-UCB/Nahual-Autenticacion-Admin pull request #5
Opened 2020-11-09 22:11 UTC by FidelRojas

2020-11-10 21:08 UTC, Kuko-CMLC requested changes, later dismissed

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesAprobadas.js
> +    this.props.estableserCargando(true);
"estableserCargando" no parece buen nombre, ademas deberia ser "establecerCargando"

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +        let dat = res;
Que es dat?

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +      console.log(res);
Eliminar este console.log

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +        mensajeDeEstado: `Se le otorgo el acceso al usuario ${value.email}`
Falta acento en "Otorgó" y punto final

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +  otorgarAcceso = async (value) => {
"value" esta en ingles, deberia ser español.

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +                header="Solicitud Aceptada!"
Deberia ser "¡Solicitud Aceptada!"

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +                          Otorgar Accesso
Dice "Otorgar Accesso".

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +      isLoading: false,
Encontrar un nombre equivalente en español para "isLoading".

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesAprobadas.js
> +                        <Button positive>Revocar Accesso</Button>
Dice "Revocar Accesso".

2020-11-10 21:08 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/Solicitudes.js
> +        content: "Solicitudes pendientes"
Es necesario que "content" este en ingles? o puede cambiarse para español?.

2020-11-10 21:11 UTC, PabloCanelas commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +    this.props.estableserCargando(true);
Al componente le llega una funcion como prop que tiene un typo. Establecer esta con S

2020-11-10 21:16 UTC, PabloCanelas commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +                          Otorgar Accesso
Acceso solo tien una S

2020-11-10 23:36 UTC, melissafg commented on src/components/lista-solicitudes/Solicitudes.js
> +        content: "Solicitudes pendientes"
tiene que ser content, no se puede cambiar :c

2020-11-11 02:32 UTC, JPC07 commented on src/components/lista-solicitudes/Solicitudes.js
> +    setEstaCargandoSolicitudesPendientes
Creo que el nombre 'setEstaCargandoSolicitudesPendientes' no se entiende bien quieren decir un conjunto de cargando solicitudes o que?

2020-11-11 02:32 UTC, JPC07 commented on src/components/lista-solicitudes/SolicitudesAprobadas.js
> +        header={`No hay solitudes aprobadas.`}
Esta mal escrito 'solicitudes'.

2020-11-11 02:35 UTC, JPC07 commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +    // try {
Porque se esta comentado todo este try? Se deberia eliminar.

2020-11-11 02:35 UTC, JPC07 commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +        header={`No hay solitudes pendientes.`}
Esta mal escrito solicitudes.

2020-11-11 04:40 UTC, johancarlos reviewed
una observacion/duda..... aca me aparece 2 carpetas "stylesheets" una con mayuscula inicial y una con minuscula, solo eso creo. https://github.com/TallerDeDesarrollo-UCB/Nahual-Autenticacion-Admin/tree/funcionalidad-195/vista-de-personas-con-acceso-otorgado/src/public

2020-11-11 04:40 UTC, JoseCarlosOliveraPeredo reviewed
Tengo pequeñas observaciones, después esta muy bien!

2020-11-11 04:40 UTC, JoseCarlosOliveraPeredo commented on src/components/lista-solicitudes/Solicitudes.js
> +              setEstaCargandoSolicitudesAprobadas(cargando)
Creo que es conveniente cambiar el nombre de función por uno mas descriptivo

2020-11-11 04:40 UTC, JoseCarlosOliveraPeredo commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +      open: false,
El nombre de esta variable debería estar en español

2020-11-11 04:40 UTC, JoseCarlosOliveraPeredo commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +        header={`Error, problema al conectar con la base de datos.`}
No deberia ser un template string, si no solo un string

2020-11-11 04:40 UTC, JoseCarlosOliveraPeredo commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +
Espacio innecesario 😁

2020-11-11 04:57 UTC, FidelRojas commented on src/components/lista-solicitudes/SolicitudesAprobadas.js
> +        header={`No hay solitudes aprobadas.`}
Corregido, gracias

2020-11-11 04:58 UTC, FidelRojas commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +    // try {
Corregido, gracias

2020-11-11 04:58 UTC, FidelRojas commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +        header={`No hay solitudes pendientes.`}
Corregido, gracias

2020-11-11 21:03 UTC, GamalSerhanOporto approved these changes

2020-11-12 16:16 UTC, Kuko-CMLC requested changes, later dismissed

2020-11-12 16:16 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +    const requestOptions = {
"requestOptions" deberia estar en español.

2020-11-12 16:16 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +                  this.state.solicitudes.map((value) => (
"value" deberia estar en español.

2020-11-12 16:16 UTC, Kuko-CMLC commented on src/components/lista-solicitudes/SolicitudesPendientes.js
> +        this.props.mostrarCargando(false);      });
Corregir este espacio "      });".

2020-11-12 16:41 UTC, merged