Funcionalidad 176/iniciar sesión en la pagina nahual admin
TallerDeDesarrollo-UCB/Nahual-Autenticacion-Admin pull request #6
Opened 2020-11-12 18:42 UTC by JoseCarlosOliveraPeredo

2020-11-13 10:19 UTC, JPC07 requested changes

2020-11-13 10:19 UTC, JPC07 commented on .env.local
> +<<<<<<< HEAD
Arreglar el rebase de esta parte.

2020-11-13 10:19 UTC, JPC07 commented on .env.prod
> +<<<<<<< HEAD
Arreglar el rebase de esta parte.

2020-11-13 10:20 UTC, JPC07 commented on src/components/Autenticacion/ValidarAutorizacion.js
> +		// eslint-disable-next-line
Porque hay este comentario?

2020-11-13 10:21 UTC, JPC07 commented on src/components/Autenticacion/ValidarAutorizacion.js
> +	const verificarAutotizacion = () => {
Esta mal escrito Autorizacion

2020-11-13 10:23 UTC, JPC07 commented on src/components/lista-solicitudes/Tabla.js
> +      open: false,
Si mal no recuerdo esto se cambio en español ?

2020-11-13 10:36 UTC, JPC07 requested changes

2020-11-13 10:36 UTC, JPC07 commented on src/components/lista-solicitudes/Tabla.js
> +import React, { Component } from "react";
No existe este archivo en la rama develop, verificar si el rebase esta bien hecho.

2020-11-13 14:43 UTC, JoseCarlosOliveraPeredo commented on .env.local
> +<<<<<<< HEAD
Resueltooo :)

2020-11-13 14:43 UTC, JoseCarlosOliveraPeredo commented on .env.prod
> +<<<<<<< HEAD
Resuelto

2020-11-13 14:44 UTC, JoseCarlosOliveraPeredo commented on src/components/Autenticacion/ValidarAutorizacion.js
> +		// eslint-disable-next-line
Al usar useEffect que es un hook, sale una advertencia en consola, para evitar esa advertencia se usa ese comentario.

2020-11-13 14:45 UTC, JoseCarlosOliveraPeredo commented on src/components/Autenticacion/ValidarAutorizacion.js
> +	const verificarAutotizacion = () => {
Corregido :), gracias

2020-11-13 14:46 UTC, JoseCarlosOliveraPeredo commented on src/components/lista-solicitudes/Tabla.js
> +import React, { Component } from "react";
Si por esa razón, al momento de hacer el rebase, preguntamos si deberíamos borrar este archivo, pero dijimos que no, ya que un equipo sigue trabajando sobre este.

2020-11-13 16:16 UTC, FidelRojas approved these changes

2020-11-13 20:37 UTC, GamalSerhanOporto approved these changes

2020-11-13 20:37 UTC, GamalSerhanOporto approved these changes

2020-11-13 20:37 UTC, GamalSerhanOporto approved these changes

2020-11-13 20:38 UTC, GamalSerhanOporto approved these changes

2020-11-14 14:52 UTC, PabloCanelas approved these changes

2020-11-15 14:19 UTC, melissafg approved these changes

2020-11-16 01:38 UTC, merged