Funcionalidad 183/boton para revocar permiso
TallerDeDesarrollo-UCB/Nahual-Autenticacion-Admin pull request #7
Opened 2020-11-12 20:57 UTC by FidelRojas

2020-11-13 10:43 UTC, JPC07 requested changes, later dismissed

2020-11-13 10:43 UTC, JPC07 commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +        console.log(respuesta);
Eliminar console log

2020-11-13 10:43 UTC, JPC07 commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +
Eliminar espacio innecesario

2020-11-13 10:43 UTC, JPC07 commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +        cuandoSerevoqueAcceso(permiso.aplicacion,respuesta.data.data)})
Deberia ser Mayuscula la R para que se entienda mejor

2020-11-13 10:43 UTC, JPC07 commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +  const cuandoSerevoqueAcceso = (aplicacion, solicitud) => {
Deberia ser Mayuscula la R

2020-11-13 10:43 UTC, JPC07 commented on src/components/lista-solicitudes/SolicitudesAprobadas.js
> +      permisos.push({ aplicacion: "Admin", color: "blue" });
Arreglar formato con los anteriores.

2020-11-13 15:12 UTC, FidelRojas commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +        console.log(respuesta);
Resuelto, muchas gracias!

2020-11-13 15:12 UTC, FidelRojas commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +
Resuelto, muchas gracias!

2020-11-13 15:12 UTC, FidelRojas commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +        cuandoSerevoqueAcceso(permiso.aplicacion,respuesta.data.data)})
Resuelto, muchas gracias!

2020-11-13 15:12 UTC, FidelRojas commented on src/components/lista-solicitudes/PermisoEtiqueta.js
> +  const cuandoSerevoqueAcceso = (aplicacion, solicitud) => {
Resuelto, muchas gracias!

2020-11-13 15:13 UTC, FidelRojas commented on src/components/lista-solicitudes/SolicitudesAprobadas.js
> +      permisos.push({ aplicacion: "Admin", color: "blue" });
Resuelto, muchas gracias!

2020-11-13 17:35 UTC, JoseCarlosOliveraPeredo commented
Tengo pequeñas observaciones, en el archivo SolicitudesPendientes.js, en las lineas 66 y 69, existe el parametro respuesta que no esta siendo usando, seria bueno quitarlo, de igual manera en la linea 82 esta el parametro error que no esta siendo usado.  
Despues me parece que todo esta bien, buen trabajo!

2020-11-13 20:35 UTC, GamalSerhanOporto approved these changes

2020-11-14 14:55 UTC, PabloCanelas approved these changes

2020-11-16 13:02 UTC, johancarlos approved these changes

2020-11-16 20:18 UTC, merged